apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-anywhere-test
  labels:
    app: eks-anywhere-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-anywhere-test
  template:
    metadata:
      annotations:
        # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/pvc: {{ include (print $.Template.BasePath "/pvc.yaml") . | sha256sum }}
      labels:
        app: eks-anywhere-test
    spec:
      containers:
        - name: hello
          image: {{ template "template.image" .Values.eksAnywhereTest }}
          ports:
            - containerPort: 80
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SECRET_NAME
              value: bar
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /config
              name: foo
            - mountPath: /secrets
              name: bar
            - name: volume
              mountPath: /pvc/
      volumes:
        - name: foo
          configMap:
            name: foo
        - name: bar
          secret:
            secretName: bar
        - name: volume
          persistentVolumeClaim:
            claimName: eks-anywhere-test
