apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  labels:
    clusterctl.cluster.x-k8s.io: ""
    clusterctl.cluster.x-k8s.io/move: ""
  name: bmctasks.bmc.tinkerbell.org
spec:
  group: bmc.tinkerbell.org
  names:
    categories:
    - tinkerbell
    kind: BMCTask
    listKind: BMCTaskList
    plural: bmctasks
    shortNames:
    - bmt
    singular: bmctask
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BMCTask is the Schema for the bmctasks API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: BMCTaskSpec defines the desired state of BMCTask
            properties:
              connection:
                description: Connection represents the BaseboardManagement connectivity
                  information.
                properties:
                  authSecretRef:
                    description: AuthSecretRef is the SecretReference that contains
                      authentication information of the BaseboardManagement. The Secret
                      must contain username and password keys.
                    properties:
                      name:
                        description: Name is unique within a namespace to reference
                          a secret resource.
                        type: string
                      namespace:
                        description: Namespace defines the space within which the
                          secret name must be unique.
                        type: string
                    type: object
                  host:
                    description: Host is the host IP address or hostname of the BaseboardManagement.
                    minLength: 1
                    type: string
                  insecureTLS:
                    description: InsecureTLS specifies trusted TLS connections.
                    type: boolean
                  port:
                    default: 623
                    description: Port is the port number for connecting with the BaseboardManagement.
                    type: integer
                required:
                - authSecretRef
                - host
                - insecureTLS
                - port
                type: object
              task:
                description: Task defines the specific action to be performed.
                maxProperties: 1
                properties:
                  oneTimeBootDeviceAction:
                    description: OneTimeBootDeviceAction represents a baseboard management
                      one time set boot device operation.
                    properties:
                      device:
                        description: Devices represents the boot devices, in order
                          for setting one time boot. Currently only the first device
                          in the slice is used to set one time boot.
                        items:
                          description: BootDevice represents boot device of the BaseboardManagement.
                          type: string
                        type: array
                      efiBoot:
                        default: false
                        description: EFIBoot specifies to EFI boot for the baseboard
                          management. When true, enables options=efiboot while setting
                          the boot device. If false, no options are passed.
                        type: boolean
                    required:
                    - device
                    type: object
                  powerAction:
                    description: PowerAction represents a baseboard management power
                      operation.
                    enum:
                    - "on"
                    - "off"
                    - soft
                    - status
                    - cycle
                    - reset
                    type: string
                type: object
            required:
            - task
            type: object
          status:
            description: BMCTaskStatus defines the observed state of BMCTask
            properties:
              completionTime:
                description: CompletionTime represents time when the task was completed.
                  The completion time is only set when the task finishes successfully.
                format: date-time
                type: string
              conditions:
                description: Conditions represents the latest available observations
                  of an object's current state.
                items:
                  properties:
                    message:
                      description: Message represents human readable message indicating
                        details about last transition.
                      type: string
                    status:
                      description: Status is the status of the BMCTask condition.
                        Can be True or False.
                      type: string
                    type:
                      description: Type of the BMCTask condition.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              startTime:
                description: StartTime represents time when the BMCTask started processing.
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
